# Generated by Django 2.0.2 on 2018-03-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='body',
            field=models.TextField(max_length='255'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='title',
            field=models.TextField(max_length='255'),
        ),
    ]
